version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: clareia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clareia
      POSTGRES_USER: clareia
      POSTGRES_PASSWORD: clareia_dev_password
    ports:
      - '5432:5432'
    volumes:
      - clareia_pg_data:/var/lib/postgresql/data

volumes:
  clareia_pg_data:
